[package]
name = "ulohy"
version = "0.1.0"
edition = "2024"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
pyo3 = { version = "0.23.3", features = ["auto-initialize"] }
rand = "0.8.5"
turtle = "1.0.0-rc.3"
